language: scala
scala:
   - 2.11.2

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y build-essential
    - git clone git://github.com/TiarkRompf/virtualization-lms-core.git
    - (cd virtualization-lms-core; sbt publish-local)
